### PR TITLE
Doc(readme): make it easier to install for most people. 

### PR DESCRIPTION
**Pull request by Codespace0x25**
make it eazey for people to use with install. 
if you need help i can help further

### CODE REVIEW

**Comment by altermo** [comment]
For the commit message, please use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
Otherwise, it looks good.

And for the help: I'm currently rewriting this in Wayland+wlroots, so that I need help with.

**Comment by Codespace0x25** [comment]
Ok what is the GitHub the that

**Comment by altermo** [comment]
To change the commit messages:
1. `$ git rebase -i HEAD~2`
2. Replace `pick` with `reword`.
3. Save and quit.
4. Edit the first commit message.
5. Save and quit.
6. Edit the second commit message.
7. Save and quit.
8. `$ git push --force`

For the commit message, I would recommend just adding `doc(readme): ` before the commit message. (remember the space after the `:`)

**Comment by Codespace0x25** [comment]
Ok I'll do it when I get home

**Comment by Codespace0x25** [comment]
Ok is this good

**Pull request merged**
